version: "3"

services:

  frontend:
    container_name: frontend
    build: 
      context: ./frontend
    ports:
      - 80:80
    networks:
      - front
    restart:
      unless-stopped

  backend:
    container_name: backend
    build: 
      context: ./lib_catalog
      dockerfile: Dockerfile-django
    ports:
      - 8000:8000
    depends_on:
      - database
    networks:
      - back
    restart:
      unless-stopped

  database:
    container_name: database
    build: 
      context: ./lib_catalog
      dockerfile: Dockerfile-db
    ports:
      - 5432:5432
    networks:
      - back
    restart:
      unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "pg_isready"]
      interval: 5s
      timeout: 3s
      retries: 3

networks:
  front:
    driver: bridge
  back:
    driver: bridge
